import {all} from 'redux-saga/effects';
import * as StationSaga from "./StationSaga";
import * as TripSaga from "./TripSaga";
import * as BusCompanySaga from "./BusCompanySaga";
import * as GlobalSaga from "./GlobalSaga";
import * as UserSaga from "./UserSaga";
import * as VehicleSaga from "./VehicleSaga";
import * as SeatSaga from "./SeatSaga";
import * as TicketSaga from "./TicketSaga";

function* rootSaga() {
    yield all([
        GlobalSaga.followGetAllArticleSaga(),
        GlobalSaga.followGetAllBannerSaga(),
        GlobalSaga.followGetAllHashtagSaga(),
        GlobalSaga.followGetAllUserTypeSaga(),
        GlobalSaga.followGetAllStatusSaga(),
        GlobalSaga.followGetAllProvinceSaga(),
        GlobalSaga.followFindArticleByIdSaga(),
        GlobalSaga.followFindBannerByIdSaga(),
        GlobalSaga.followFindHashtagByIdSaga(),
        GlobalSaga.followFindHashtagByNameSaga(),
        GlobalSaga.followFindUserTypeByIdSaga(),
        GlobalSaga.followFindStatusByIdSaga(),
        GlobalSaga.followFindProvinceByIdSaga(),
        GlobalSaga.followEditArticleSaga(),
        GlobalSaga.followEditBannerSaga(),
        GlobalSaga.followEditHashtagSaga(),
        GlobalSaga.followEditUserTypeSaga(),
        GlobalSaga.followEditStatusSaga(),
        GlobalSaga.followEditProvinceSaga(),
        GlobalSaga.followDeleteArticleSaga(),
        GlobalSaga.followGetArticleByHashTagAndTitleSaga(),
        GlobalSaga.followDeleteBannerSaga(),
        GlobalSaga.followDeleteHashtagSaga(),
        GlobalSaga.followDeleteUserTypeSaga(),
        GlobalSaga.followDeleteStatusSaga(),
        GlobalSaga.followDeleteProvinceSaga(),
        GlobalSaga.followAddArticleSaga(),
        GlobalSaga.followAddBannerSaga(),
        GlobalSaga.followAddHashtagSaga(),
        GlobalSaga.followAddUserTypeSaga(),
        GlobalSaga.followAddStatusSaga(),
        GlobalSaga.followAddProvinceSaga(),
        GlobalSaga.followGetAllBusTypeSaga(),
        GlobalSaga.followAddBusTypeSaga(),
        GlobalSaga.followEditBusTypeSaga(),
        GlobalSaga.followDeleteBusTypeSaga(),
        GlobalSaga.followFindBusTypeByIdSaga(),
        GlobalSaga.followGetAllPaymentMethodSaga(),
        GlobalSaga.followAddPaymentMethodSaga(),
        GlobalSaga.followEditPaymentMethodSaga(),
        GlobalSaga.followDeletePaymentMethodSaga(),
        GlobalSaga.followFindPaymentMethodByIdSaga(),
        GlobalSaga.followAddPointSaga(),
        GlobalSaga.followEditPointSaga(),
        GlobalSaga.followFindPointByIdSaga(),
        GlobalSaga.followDeletePointSaga(),
        GlobalSaga.followGetAllPointSaga(),
        GlobalSaga.followAddPaymentStatusSaga(),
        GlobalSaga.followEditPaymentStatusSaga(),
        GlobalSaga.followFindPaymentStatusByIdSaga(),
        GlobalSaga.followDeletePaymentStatusSaga(),
        GlobalSaga.followGetAllPaymentStatusSaga(),
        GlobalSaga.followAddOrderStatusSaga(),
        GlobalSaga.followEditOrderStatusSaga(),
        GlobalSaga.followFindOrderStatusByIdSaga(),
        GlobalSaga.followDeleteOrderStatusSaga(),
        GlobalSaga.followGetAllOrderStatusSaga(),
        StationSaga.followGetAllStationSaga(),
        StationSaga.followAddStationSaga(),
        StationSaga.followEditStationSaga(),
        StationSaga.followDeleteStationSaga(),
        StationSaga.followFindStationByIdSaga(),
        StationSaga.followFindStationByKeywordSaga(),
        TripSaga.followGetTripSaga(),
        TripSaga.followAddTripSaga(),
        TripSaga.followEditTripSaga(),
        TripSaga.followDeleteTripSaga(),
        TripSaga.followFindTripByIdSaga(),
        TripSaga.followFindTripByKeywordSaga(),
        BusCompanySaga.followGetAllBusCompanySaga(),
        BusCompanySaga.followAddBusCompanySaga(),
        BusCompanySaga.followEditBusCompanySaga(),
        BusCompanySaga.followDeleteBusCompanySaga(),
        BusCompanySaga.followFindBusCompanyByIdSaga(),
        BusCompanySaga.followFindBusCompanyByKeywordSaga(),
        VehicleSaga.followGetAllVehicleSaga(),
        VehicleSaga.followAddVehicleSaga(),
        VehicleSaga.followEditVehicleSaga(),
        VehicleSaga.followDeleteVehicleSaga(),
        VehicleSaga.followFindVehicleByIdSaga(),
        VehicleSaga.followFindVehicleByKeywordSaga(),
        VehicleSaga.followFindVehicleFollowTripDateSaga(),
        SeatSaga.followGetAllSeatSaga(),
        SeatSaga.followAddSeatSaga(),
        SeatSaga.followEditSeatSaga(),
        SeatSaga.followDeleteSeatSaga(),
        SeatSaga.followFindSeatByIdSaga(),
        SeatSaga.followFindSeatByKeywordSaga(),
        UserSaga.followLoginSaga(),
        UserSaga.followRegisterSaga(),
        UserSaga.followGetAllUserSaga(),
        UserSaga.followAddUserSaga(),
        UserSaga.followEditUserSaga(),
        UserSaga.followUpdateProfileSaga(),
        UserSaga.followDeleteUserSaga(),
        UserSaga.followGetUserByIdSaga(),
        UserSaga.followGetUserByKeywordSaga(),
        TicketSaga.followGetAllTicketSaga(),
        TicketSaga.followAddTicketSaga(),
        TicketSaga.followEditTicketSaga(),
        TicketSaga.followDeleteTicketSaga(),
        TicketSaga.followFindTicketByIdSaga(),
        TicketSaga.followFindTicketByKeywordSaga(),
        TicketSaga.followFilterTickByEmailSaga(),
        TicketSaga.followSubmitCheckoutSaga()
    ]);
}

export default rootSaga;