export const GET_BUS_COMPANY = 'GET_BUS_COMPANY';
export const GET_BUS_COMPANY_SAGA = 'GET_BUS_COMPANY_SAGA';

export const DELETE_BUS_COMPANY_SAGA = 'DELETE_BUS_COMPANY_SAGA';
export const ADD_BUS_COMPANY_SAGA = 'ADD_BUS_COMPANY_SAGA';
export const EDIT_BUS_COMPANY_SAGA = 'EDIT_BUS_COMPANY_SAGA';

export const FIND_BUS_COMPANY_BY_KEYWORD = 'FIND_BUS_COMPANY_BY_KEYWORD';
export const FIND_BUS_COMPANY_BY_KEYWORD_SAGA = 'FIND_BUS_COMPANY_BY_KEYWORD_SAGA';
export const FIND_BUS_COMPANY_BY_ID = 'FIND_BUS_COMPANY_BY_ID';
export const FIND_BUS_COMPANY_BY_ID_SAGA = 'FIND_BUS_COMPANY_BY_ID_SAGA';