export const SET_SEAT_CURRENT = 'SET_SEAT_CURRENT';
export const SET_POINT_CURRENT = 'SET_POINT_CURRENT';
export const SET_USER_CHECKOUT_CURRENT = 'SET_USER_CHECKOUT_CURRENT';
export const SET_SUBMIT_NEXT_CHECKOUT = 'SET_SUBMIT_NEXT_CHECKOUT';
export const SET_PAYMENT_CHECKOUT = 'SET_PAYMENT_CHECKOUT';
export const SUBMIT_PAYMENT_CHECKOUT = 'SUBMIT_PAYMENT_CHECKOUT';
export const SUBMIT_PAYMENT_CHECKOUT_SAGA = 'SUBMIT_PAYMENT_CHECKOUT_SAGA';
export const CLEAR_PAYMENT_CHECKOUT = 'CLEAR_PAYMENT_CHECKOUT';