export const SHOW_DRAWER = 'SHOW_DRAWER';
export const HIDE_DRAWER = 'HIDE_DRAWER';

export const SET_CALLBACK_DRAWER = 'SET_CALLBACK_DRAWER';
export const RESET_CALLBACK_DRAWER = 'RESET_CALLBACK_DRAWER';

export const SET_CONTENT_DRAWER = 'SET_CONTENT_DRAWER';
