export const GET_ARTICLE = 'GET_ARTICLE';
export const GET_ARTICLE_SAGA = 'GET_ARTICLE_SAGA';
export const DELETE_ARTICLE_SAGA = 'DELETE_ARTICLE_SAGA';
export const ADD_ARTICLE_SAGA = 'ADD_ARTICLE_SAGA';
export const EDIT_ARTICLE_SAGA = 'EDIT_ARTICLE_SAGA';
export const FIND_ARTICLE_BY_ID = 'FIND_ARTICLE_BY_ID';
export const FIND_ARTICLE_BY_ID_SAGA = 'FIND_ARTICLE_BY_ID_SAGA';
export const FIND_ARTICLE_BY_HASHTAG_AND_TITLE = 'FIND_ARTICLE_BY_HASHTAG_AND_TITLE';
export const FIND_ARTICLE_BY_HASHTAG_AND_TITLE_SAGA = 'FIND_ARTICLE_BY_HASHTAG_AND_TITLE_SAGA';

export const GET_ALL_BANNER = 'GET_ALL_BANNER';
export const GET_ALL_BANNER_SAGA = 'GET_ALL_BANNER_SAGA';
export const DELETE_BANNER_SAGA = 'DELETE_BANNER_SAGA';
export const ADD_BANNER_SAGA = 'ADD_BANNER_SAGA';
export const EDIT_BANNER_SAGA = 'EDIT_BANNER_SAGA';
export const FIND_BANNER_BY_ID = 'FIND_BANNER_BY_ID';
export const FIND_BANNER_BY_ID_SAGA = 'FIND_BANNER_BY_ID_SAGA';

export const GET_ALL_HASHTAG = 'GET_ALL_HASHTAG';
export const GET_ALL_HASHTAG_SAGA = 'GET_ALL_HASHTAG_SAGA';
export const DELETE_HASHTAG_SAGA = 'DELETE_HASHTAG_SAGA';
export const ADD_HASHTAG_SAGA = 'ADD_HASHTAG_SAGA';
export const EDIT_HASHTAG_SAGA = 'EDIT_HASHTAG_SAGA';
export const FIND_HASHTAG_BY_ID = 'FIND_HASHTAG_BY_ID';
export const FIND_HASHTAG_BY_ID_SAGA = 'FIND_HASHTAG_BY_ID_SAGA';
export const FIND_HASHTAG_BY_NAME = 'FIND_HASHTAG_BY_NAME';
export const FIND_HASHTAG_BY_NAME_SAGA = 'FIND_HASHTAG_BY_NAME_SAGA';

export const GET_ALL_USERTYPE = 'GET_ALL_USERTYPE';
export const GET_ALL_USERTYPE_SAGA = 'GET_ALL_USERTYPE_SAGA';
export const DELETE_USERTYPE_SAGA = 'DELETE_USERTYPE_SAGA';
export const ADD_USERTYPE_SAGA = 'ADD_USERTYPE_SAGA';
export const EDIT_USERTYPE_SAGA = 'EDIT_USERTYPE_SAGA';
export const FIND_USERTYPE_BY_ID = 'FIND_USERTYPE_BY_ID';
export const FIND_USERTYPE_BY_ID_SAGA = 'FIND_USERTYPE_BY_ID_SAGA';

export const GET_ALL_STATUS = 'GET_ALL_STATUS';
export const GET_ALL_STATUS_SAGA = 'GET_ALL_STATUS_SAGA';
export const DELETE_STATUS_SAGA = 'DELETE_STATUS_SAGA';
export const ADD_STATUS_SAGA = 'ADD_STATUS_SAGA';
export const EDIT_STATUS_SAGA = 'EDIT_STATUS_SAGA';
export const FIND_STATUS_BY_ID = 'FIND_STATUS_BY_ID';
export const FIND_STATUS_BY_ID_SAGA = 'FIND_STATUS_BY_ID_SAGA';

export const GET_ALL_PROVINCE = 'GET_ALL_PROVINCE';
export const GET_ALL_PROVINCE_SAGA = 'GET_ALL_PROVINCE_SAGA';
export const DELETE_PROVINCE_SAGA = 'DELETE_PROVINCE_SAGA';
export const ADD_PROVINCE_SAGA = 'ADD_PROVINCE_SAGA';
export const EDIT_PROVINCE_SAGA = 'EDIT_PROVINCE_SAGA';
export const FIND_PROVINCE_BY_ID = 'FIND_PROVINCE_BY_ID';
export const FIND_PROVINCE_BY_ID_SAGA = 'FIND_PROVINCE_BY_ID_SAGA';

export const GET_ALL_POINT = 'GET_ALL_POINT';
export const GET_ALL_POINT_SAGA = 'GET_ALL_POINT_SAGA';
export const DELETE_POINT_SAGA = 'DELETE_POINT_SAGA';
export const ADD_POINT_SAGA = 'ADD_POINT_SAGA';
export const EDIT_POINT_SAGA = 'EDIT_POINT_SAGA';
export const FIND_POINT_BY_ID = 'FIND_POINT_BY_ID';
export const FIND_POINT_BY_ID_SAGA = 'FIND_POINT_BY_ID_SAGA';

export const GET_ALL_PAYMENT_STATUS = 'GET_ALL_PAYMENT_STATUS';
export const GET_ALL_PAYMENT_STATUS_SAGA = 'GET_ALL_PAYMENT_STATUS_SAGA';
export const DELETE_PAYMENT_STATUS_SAGA = 'DELETE_PAYMENT_STATUS_SAGA';
export const ADD_PAYMENT_STATUS_SAGA = 'ADD_PAYMENT_STATUS_SAGA';
export const EDIT_PAYMENT_STATUS_SAGA = 'EDIT_PAYMENT_STATUS_SAGA';
export const FIND_PAYMENT_STATUS_BY_ID = 'FIND_PAYMENT_STATUS_BY_ID';
export const FIND_PAYMENT_STATUS_BY_ID_SAGA = 'FIND_PAYMENT_STATUS_BY_ID_SAGA';

export const GET_ALL_ORDER_STATUS = 'GET_ALL_ORDER_STATUS';
export const GET_ALL_ORDER_STATUS_SAGA = 'GET_ALL_ORDER_STATUS_SAGA';
export const DELETE_ORDER_STATUS_SAGA = 'DELETE_ORDER_STATUS_SAGA';
export const ADD_ORDER_STATUS_SAGA = 'ADD_ORDER_STATUS_SAGA';
export const EDIT_ORDER_STATUS_SAGA = 'EDIT_ORDER_STATUS_SAGA';
export const FIND_ORDER_STATUS_BY_ID = 'FIND_ORDER_STATUS_BY_ID';
export const FIND_ORDER_STATUS_BY_ID_SAGA = 'FIND_ORDER_STATUS_BY_ID_SAGA';

export const GET_ALL_BUSTYPE = 'GET_ALL_BUSTYPE';
export const GET_ALL_BUSTYPE_SAGA = 'GET_ALL_BUSTYPE_SAGA';
export const DELETE_BUSTYPE_SAGA = 'DELETE_BUSTYPE_SAGA';
export const ADD_BUSTYPE_SAGA = 'ADD_BUSTYPE_SAGA';
export const EDIT_BUSTYPE_SAGA = 'EDIT_BUSTYPE_SAGA';
export const FIND_BUSTYPE_BY_ID = 'FIND_BUSTYPE_BY_ID';
export const FIND_BUSTYPE_BY_ID_SAGA = 'FIND_BUSTYPE_BY_ID_SAGA';

export const GET_ALL_PAYMENT_METHOD = 'GET_ALL_PAYMENT_METHOD';
export const GET_ALL_PAYMENT_METHOD_SAGA = 'GET_ALL_PAYMENT_METHOD_SAGA';
export const DELETE_PAYMENT_METHOD_SAGA = 'DELETE_PAYMENT_METHOD_SAGA';
export const ADD_PAYMENT_METHOD_SAGA = 'ADD_PAYMENT_METHOD_SAGA';
export const EDIT_PAYMENT_METHOD_SAGA = 'EDIT_PAYMENT_METHOD_SAGA';
export const FIND_PAYMENT_METHOD_BY_ID = 'FIND_PAYMENT_METHOD_BY_ID';
export const FIND_PAYMENT_METHOD_BY_ID_SAGA = 'FIND_PAYMENT_METHOD_BY_ID_SAGA';