export const GET_ALL_SEAT = 'GET_ALL_SEAT';
export const GET_ALL_SEAT_SAGA = 'GET_ALL_SEAT_SAGA';

export const DELETE_SEAT_SAGA = 'DELETE_SEAT_SAGA';
export const ADD_SEAT_SAGA = 'ADD_SEAT_SAGA';
export const EDIT_SEAT_SAGA = 'EDIT_SEAT_SAGA';

export const FIND_SEAT_BY_KEYWORD = 'FIND_SEAT_BY_KEYWORD';
export const FIND_SEAT_BY_KEYWORD_SAGA = 'FIND_SEAT_BY_KEYWORD_SAGA';
export const FIND_SEAT_BY_ID = 'FIND_SEAT_BY_ID';
export const FIND_SEAT_BY_ID_SAGA = 'FIND_SEAT_BY_ID_SAGA';
