export const GET_ALL_STATION = 'GET_ALL_STATION';
export const GET_ALL_STATION_SAGA = 'GET_ALL_STATION_SAGA';

export const DELETE_STATION_SAGA = 'DELETE_STATION_SAGA';
export const ADD_STATION_SAGA = 'ADD_STATION_SAGA';
export const EDIT_STATION_SAGA = 'EDIT_STATION_SAGA';

export const FIND_STATION_BY_KEYWORD = 'FIND_STATION_BY_KEYWORD';
export const FIND_STATION_BY_KEYWORD_SAGA = 'FIND_STATION_BY_KEYWORD_SAGA';
export const FIND_STATION_BY_ID = 'FIND_STATION_BY_ID';
export const FIND_STATION_BY_ID_SAGA = 'FIND_STATION_BY_ID_SAGA';