export const GET_ALL_TICKET = 'GET_ALL_TICKET';
export const GET_ALL_TICKET_SAGA = 'GET_ALL_TICKET_SAGA';

export const DELETE_TICKET_SAGA = 'DELETE_TICKET_SAGA';
export const ADD_TICKET_SAGA = 'ADD_TICKET_SAGA';
export const EDIT_TICKET_SAGA = 'EDIT_TICKET_SAGA';

export const FIND_TICKET_BY_KEYWORD = 'FIND_TICKET_BY_KEYWORD';
export const FIND_TICKET_BY_KEYWORD_SAGA = 'FIND_TICKET_BY_KEYWORD_SAGA';
export const FIND_TICKET_BY_ID = 'FIND_TICKET_BY_ID';
export const FIND_TICKET_BY_ID_SAGA = 'FIND_TICKET_BY_ID_SAGA';
export const FILTER_TICKET_BY_EMAIL = 'FILTER_TICKET_BY_EMAIL';
export const FILTER_TICKET_BY_EMAIL_SAGA = 'FILTER_TICKET_BY_EMAIL_SAGA';