export const GET_ALL_VEHICLE = 'GET_VEHICLE';
export const GET_ALL_VEHICLE_SAGA = 'GET_VEHICLE_SAGA';

export const DELETE_VEHICLE_SAGA = 'DELETE_VEHICLE_SAGA';
export const ADD_VEHICLE_SAGA = 'ADD_VEHICLE_SAGA';
export const EDIT_VEHICLE_SAGA = 'EDIT_VEHICLE_SAGA';

export const FIND_VEHICLE_BY_KEYWORD = 'FIND_VEHICLE_BY_KEYWORD';
export const FIND_VEHICLE_BY_KEYWORD_SAGA = 'FIND_VEHICLE_BY_KEYWORD_SAGA';
export const FIND_VEHICLE_BY_ID = 'FIND_VEHICLE_BY_ID';
export const FIND_VEHICLE_BY_ID_SAGA = 'FIND_VEHICLE_BY_ID_SAGA';

export const FIND_VEHICLE_BY_TRIP_BUS = 'FIND_VEHICLE_BY_TRIP_BUS';
export const FIND_VEHICLE_BY_TRIP_BUS_SAGA = 'FIND_VEHICLE_BY_TRIP_BUS_SAGA';

export const SORT_BUS_TRIP = 'SORT_BUS_TRIP';
